<a href="https://colab.research.google.com/github/LS10432/PDDS-PYD-0825-06Oct2025B/blob/main/02/Assignment_02a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Task 1: Convert Weights to Pounds
* Create a Python list *weight_kg* with weight values
* Convert *weight_kg* to numpy array *np_weight_kg*
* Convert *np_weight_kg* to weight in Pounds *np_weight_lbs*

Hint: Use the conversion factor of 2.2 pounds per kilogram

In [2]:
# Import NumPy library into script and gives it an alias 'np'
import numpy as np

# Use the provided Python list of weights in kg
weight_kg = [66, 77, 88, 99, 101]

# Convert the input list to a numpy array
np_weight_kg = np.array(weight_kg)

# Convert weight from kg to pounds (1 kg = 2.2 lbs)
np_weight_lbs = np_weight_kg * 2.2

# Print the results in kg
print(f"\nWeight in kg: {weight_kg}")

# Print the results in pounds
print(f"Weight in lbs: {np_weight_lbs}")


Weight in kg: [66, 77, 88, 99, 101]
Weight in lbs: [145.2 169.4 193.6 217.8 222.2]


### Task 2: Calculate Mean and Median

* Write a NumPy program to calculate the mean and median of the weights in pounds. Print out the results.

In [7]:
# Calculate the mean of the weights in pounds
mean_weight_lbs = np.mean(np_weight_lbs)

# Print the Mean weight in pounds to 2 decimal places
print(f"\nMean weight in lbs: {mean_weight_lbs:.2f}")

# Calculate the median of the weights in pounds
median_weight_lbs = np.median(np_weight_lbs)

# Print the Median weight in pounds to 2 decimal places
print(f"Median weight in lbs: {median_weight_lbs:.2f}")


Mean weight in lbs: 189.64
Median weight in lbs: 193.60


### Task 3: Create 2D Array
* Create a NumPy array *np_height_m* containing the heights of individuals in meters.
* Combine this array with the weights in pounds *np_weight_lbs* to create a 2D array *np_person_info* where each row represents an individual's height and weight.
* Print the resulting 2D array.

In [4]:
# Create a NumPy array containing the heights of individuals in meters
np_height_m = np.array([1.6, 1.7, 1.8, 1.9, 2.1])

# Combine height and weight arrays to create a 2D array
# Each row contains [height (m), weight (lbs)] for an individual
np_person_info = np.column_stack((np_height_m, np_weight_lbs))

# Print a newline followed by a separator line
print("\n" + "="*60)
# Print section header for person information
print("PERSON INFORMATION")
# Print separator line
print("="*60)

# Print result in 2D array
print("[Height (m), Weight (lbs)]")
print(np_person_info)


PERSON INFORMATION
[Height (m), Weight (lbs)]
[[  1.6 145.2]
 [  1.7 169.4]
 [  1.8 193.6]
 [  1.9 217.8]
 [  2.1 222.2]]


### Task 4: Calculate BMI
* Write a function that takes the 2D array *np_person_info* created in Task 3 as input.
* Calculate the Body Mass Index (BMI) for each individual as *bmi_array*. BMI is calculated using the formula: BMI = weight (kg) / (height (m) ** 2).
* Print the BMI values for each individual.

In [8]:
# Define a function named 'calculate_bmi' to calculate BMI from the 2D array 'np_person_info'
def calculate_bmi(person_info):
  # Extract height (column 0) and weight in lbs (column 1) from the 2D array
  heights = person_info[:, 0]
  weights_lbs = person_info[:, 1]

  # Convert weight from pounds to kg (1 lb = 1 kg / 2.2)
  weights_kg = weights_lbs / 2.2

  # Calculate BMI using the formula: BMI = weight (kg) / (height (m) ** 2)
  bmi_array = weights_kg / (heights ** 2)

  # Return the calculated BMI array
  return bmi_array

# Call the function 'calculate_bmi' to calculate BMI for each individual
bmi_array = calculate_bmi(np_person_info)

# Print a newline followed by a separator line
print("\n" + "="*60)
# Print section header for BMI values
print("BMI VALUES")
# Print separator line
print("="*60)

# Iterate through 'bmi_array' to get each individual 'bmi_value' value
for i, bmi_value in enumerate(bmi_array):
  # Print the BMI for each individual and format the 'bmi_value' to 2 decimal places
  print(f"Individual {i+1}: {bmi_value:.2f}")


BMI VALUES
Individual 1: 25.78
Individual 2: 26.64
Individual 3: 27.16
Individual 4: 27.42
Individual 5: 22.90


### Task 5: Filter Individuals by BMI
* Write a NumPy program to append *bmi_array* to *np_person_info*
* Filter individuals from the resulting array who have a BMI greater than 25.
* Print the filtered results.

In [10]:
# Reshape bmi_array to a column vector for appending
bmi_column = bmi_array.reshape(-1, 1)

# Append bmi_array as a new column to np_person_info
# Each row now contains [height, weight, bmi]
np_person_info = np.column_stack((np_person_info, bmi_column))

# Print a newline followed by a separator line
print("\n" + "="*60)
# Print section header for updated person information with BMI
print("UPDATED PERSON INFORMATION WITH BMI")
# Print separator line
print("="*60)

# Print the updated 2D array with BMI column
print("[Height (m), Weight (lbs), BMI]")
print(np_person_info)

# Print a newline followed by a separator line
print("\n" + "="*60)
# Print section header for filtered results
print("FILTERED RESULTS (BMI > 25)")
# Print separator line
print("="*60)

# Filter individuals with BMI greater than 25
# Create a boolean mask where BMI (column 2) is greater than 25
filtered_person_info = np_person_info[np_person_info[:, 2] > 25]

# Check if any individuals have BMI greater than 25
if len(filtered_person_info) > 0:
  # Display format explanation for filtered results
  print("[Height (m), Weight (lbs), BMI]")
  # Display the filtered 2D array
  print(filtered_person_info)
else:
  # Display message indicating no matches found
  print("No individuals have BMI greater than 25.")


UPDATED PERSON INFORMATION WITH BMI
[Height (m), Weight (lbs), BMI]
[[  1.6        145.2         25.78125     25.78125   ]
 [  1.7        169.4         26.64359862  26.64359862]
 [  1.8        193.6         27.16049383  27.16049383]
 [  1.9        217.8         27.42382271  27.42382271]
 [  2.1        222.2         22.90249433  22.90249433]]

FILTERED RESULTS (BMI > 25)
[Height (m), Weight (lbs), BMI]
[[  1.6        145.2         25.78125     25.78125   ]
 [  1.7        169.4         26.64359862  26.64359862]
 [  1.8        193.6         27.16049383  27.16049383]
 [  1.9        217.8         27.42382271  27.42382271]]
