<a href="https://colab.research.google.com/github/LS10432/PDDS-PYD-0825-06Oct2025B/blob/main/02/Assignment_02a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Task 1: Convert Weights to Pounds
* Create a Python list *weight_kg* with weight values
* Convert *weight_kg* to numpy array *np_weight_kg*
* Convert *np_weight_kg* to weight in Pounds *np_weight_lbs*

Hint: Use the conversion factor of 2.2 pounds per kilogram

In [ ]:
# Import NumPy library into script and gives it an alias 'np'
import numpy as np

# Initialize an empty list to store weight values
weight_kg = []

# Loop until the user provides valid input
while True:
  # Get user input as a string
  user_input = input("Please enter weight values in kg separated by spaces ' ': ")
  # Split the input into parts
  parts = user_input.split()

  # Check if at least one weight value was entered
  if len(parts) == 0:
    print("Error: Please enter at least one weight value.")
    continue

  # Try to convert all inputs to floats
  try:
    weight_kg = list(map(float, parts))

    # Check if any weight value is negative
    if any(weight < 0 for weight in weight_kg):
      print("Error: Weight values cannot be negative.")
      continue

    # Exit the loop if all conversions are successful
    break
  except ValueError:
    # Print error message if any input is not a valid number
    print("Error: All inputs must be valid numbers.")

# Convert the input list to a numpy array
np_weight_kg = np.array(weight_kg)

# Convert weight from kg to pounds (1 kg = 2.2 lbs)
np_weight_lbs = np_weight_kg * 2.2

# Print the results in kg
print(f"\nWeight in kg: {np_weight_kg}")

# Print the results in pounds
print(f"Weight in lbs: {np_weight_lbs}")

Please enter weight values in kg separated by spaces ' ': 
Error: Please enter at least one weight value.
Please enter weight values in kg separated by spaces ' ': asd
Error: All inputs must be valid numbers.
Please enter weight values in kg separated by spaces ' ': asd 345
Error: All inputs must be valid numbers.
Please enter weight values in kg separated by spaces ' ': 124 sdeffa
Error: All inputs must be valid numbers.
Please enter weight values in kg separated by spaces ' ': 1 3 567 890 312       99

Weight in kg: [  1.   3. 567. 890. 312.  99.]
Weight in lbs: [   2.2    6.6 1247.4 1958.   686.4  217.8]


### Task 2: Calculate Mean and Median

* Write a NumPy program to calculate the mean and median of the weights in pounds. Print out the results.

In [ ]:
# Import NumPy library into script and gives it an alias 'np'
import numpy as np

# Initialize an empty list to store weight values
weight_kg = []

# Loop until the user provides valid input
while True:
  # Get user input as a string
  user_input = input("Please enter weight values in kg separated by spaces ' ': ")
  # Split the input into parts
  parts = user_input.split()

  # Check if at least one weight value was entered
  if len(parts) == 0:
    print("Error: Please enter at least one weight value.")
    continue

  # Try to convert all inputs to floats
  try:
    weight_kg = list(map(float, parts))

    # Check if any weight value is negative
    if any(weight < 0 for weight in weight_kg):
      print("Error: Weight values cannot be negative.")
      continue

    # Exit the loop if all conversions are successful
    break
  except ValueError:
    # Print error message if any input is not a valid number
    print("Error: All inputs must be valid numbers.")

# Convert the input list to a numpy array
np_weight_kg = np.array(weight_kg)

# Convert weight from kg to pounds (1 kg = 2.2 lbs)
np_weight_lbs = np_weight_kg * 2.2

# Print the results in kg
print(f"\nWeight in kg: {np_weight_kg}")

# Print the results in pounds
print(f"Weight in lbs: {np_weight_lbs}")

# Calculate the mean of the weights in pounds
mean_weight_lbs = np.mean(np_weight_lbs)

# Calculate the median of the weights in pounds
median_weight_lbs = np.median(np_weight_lbs)

# Print the mean weight in pounds
print(f"\nMean weight: {mean_weight_lbs:.2f} lbs")

# Print the median weight in pounds
print(f"Median weight: {median_weight_lbs:.2f} lbs")

Please enter weight values in kg separated by spaces ' ': 23 56 89 67 57 89 99

Weight in kg: [23. 56. 89. 67. 57. 89. 99.]
Weight in lbs: [ 50.6 123.2 195.8 147.4 125.4 195.8 217.8]

Mean weight: 150.86 lbs
Median weight: 147.40 lbs


### Task 3: Create 2D Array
* Create a NumPy array *np_height_m* containing the heights of individuals in meters.
* Combine this array with the weights in pounds *np_weight_lbs* to create a 2D array *np_person_info* where each row represents an individual's height and weight.
* Print the resulting 2D array.

In [ ]:
# Import NumPy library into script and gives it an alias 'np'
import numpy as np

# Initialize an empty list to store weight values
weight_kg = []

# Loop until the user provides valid input
while True:
  # Get user input as a string
  user_input = input("Please enter weight values in kg separated by spaces ' ': ")
  # Split the input into parts
  parts = user_input.split()

  # Check if at least one weight value was entered
  if len(parts) == 0:
    print("Error: Please enter at least one weight value.")
    continue

  # Try to convert all inputs to floats
  try:
    weight_kg = list(map(float, parts))

    # Check if any weight value is negative
    if any(weight < 0 for weight in weight_kg):
      print("Error: Weight values cannot be negative.")
      continue

    # Exit the loop if all conversions are successful
    break
  except ValueError:
    # Print error message if any input is not a valid number
    print("Error: All inputs must be valid numbers.")

# Convert the input list to a numpy array
np_weight_kg = np.array(weight_kg)

# Convert weight from kg to pounds (1 kg = 2.2 lbs)
np_weight_lbs = np_weight_kg * 2.2

# Print the results in kg
print(f"\nWeight in kg: {np_weight_kg}")

# Print the results in pounds
print(f"Weight in lbs: {np_weight_lbs}")

# Calculate the mean of the weights in pounds
mean_weight_lbs = np.mean(np_weight_lbs)

# Calculate the median of the weights in pounds
median_weight_lbs = np.median(np_weight_lbs)

# Print the mean weight in pounds
print(f"\nMean weight: {mean_weight_lbs:.2f} lbs")

# Print the median weight in pounds
print(f"Median weight: {median_weight_lbs:.2f} lbs")

# Initialize an empty list to store height values
height_m = []

# Loop until the user provides valid input for heights
while True:
  # Get user input as a string
  user_input = input("\nPlease enter height values in meters separated by spaces ' ': ")
  # Split the input into parts
  parts = user_input.split()

  # Check if the number of heights matches the number of weights
  if len(parts) != len(weight_kg):
    print(f"Error: Please enter exactly {len(weight_kg)} height value(s) to match the number of weights.")
    continue

  # Try to convert all inputs to floats
  try:
    height_m = list(map(float, parts))

    # Check if any height value is negative or zero
    if any(height <= 0 for height in height_m):
      print("Error: Height values must be positive.")
      continue

    # Exit the loop if all conversions are successful
    break
  except ValueError:
    # Print error message if any input is not a valid number
    print("Error: All inputs must be valid numbers.")

# Convert the height list to a numpy array
np_height_m = np.array(height_m)

# Combine height and weight arrays to create a 2D array
# Each row contains [height, weight] for an individual
np_person_info = np.column_stack((np_height_m, np_weight_lbs))

# Print the 2D array
print(f"\nPerson Info (Height in meters, Weight in lbs):")
print(np_person_info)

Please enter weight values in kg separated by spaces ' ': 67 89 99

Weight in kg: [67. 89. 99.]
Weight in lbs: [147.4 195.8 217.8]

Mean weight: 187.00 lbs
Median weight: 195.80 lbs

Please enter height values in meters separated by spaces ' ': 1.1 
Error: Please enter exactly 3 height value(s) to match the number of weights.

Please enter height values in meters separated by spaces ' ': 1.1 asfa 1.9
Error: All inputs must be valid numbers.

Please enter height values in meters separated by spaces ' ': 1.2 1.5. 1.49
Error: All inputs must be valid numbers.

Please enter height values in meters separated by spaces ' ': 1.5 1.8 -0.5
Error: Height values must be positive.

Please enter height values in meters separated by spaces ' ': 1.5 1.6 1.7

Person Info (Height in meters, Weight in lbs):
[[  1.5 147.4]
 [  1.6 195.8]
 [  1.7 217.8]]


### Task 4: Calculate BMI
* Write a function that takes the 2D array *np_person_info* created in Task 3 as input.
* Calculate the Body Mass Index (BMI) for each individual as *bmi_array*. BMI is calculated using the formula: BMI = weight (kg) / (height (m) ** 2).
* Print the BMI values for each individual.

In [ ]:
# Import NumPy library into script and gives it an alias 'np'
import numpy as np

# Initialize an empty list to store weight values
weight_kg = []

# Loop until the user provides valid input
while True:
  # Get user input as a string
  user_input = input("Please enter weight values in kg separated by spaces ' ': ")
  # Split the input into parts
  parts = user_input.split()

  # Check if at least one weight value was entered
  if len(parts) == 0:
    print("Error: Please enter at least one weight value.")
    continue

  # Try to convert all inputs to floats
  try:
    weight_kg = list(map(float, parts))

    # Check if any weight value is negative
    if any(weight < 0 for weight in weight_kg):
      print("Error: Weight values cannot be negative.")
      continue

    # Exit the loop if all conversions are successful
    break
  except ValueError:
    # Print error message if any input is not a valid number
    print("Error: All inputs must be valid numbers.")

# Convert the input list to a numpy array
np_weight_kg = np.array(weight_kg)

# Convert weight from kg to pounds (1 kg = 2.2 lbs)
np_weight_lbs = np_weight_kg * 2.2

# Print the results in kg
print(f"\nWeight in kg: {np_weight_kg}")

# Print the results in pounds
print(f"Weight in lbs: {np_weight_lbs}")

# Calculate the mean of the weights in pounds
mean_weight_lbs = np.mean(np_weight_lbs)

# Calculate the median of the weights in pounds
median_weight_lbs = np.median(np_weight_lbs)

# Print the mean weight in pounds
print(f"\nMean weight: {mean_weight_lbs:.2f} lbs")

# Print the median weight in pounds
print(f"Median weight: {median_weight_lbs:.2f} lbs")

# Initialize an empty list to store height values
height_m = []

# Loop until the user provides valid input for heights
while True:
  # Get user input as a string
  user_input = input("\nPlease enter height values in meters separated by spaces ' ': ")
  # Split the input into parts
  parts = user_input.split()

  # Check if the number of heights matches the number of weights
  if len(parts) != len(weight_kg):
    print(f"Error: Please enter exactly {len(weight_kg)} height value(s) to match the number of weights.")
    continue

  # Try to convert all inputs to floats
  try:
    height_m = list(map(float, parts))

    # Check if any height value is negative or zero
    if any(height <= 0 for height in height_m):
      print("Error: Height values must be positive.")
      continue

    # Exit the loop if all conversions are successful
    break
  except ValueError:
    # Print error message if any input is not a valid number
    print("Error: All inputs must be valid numbers.")

# Convert the height list to a numpy array
np_height_m = np.array(height_m)

# Combine height and weight arrays to create a 2D array
# Each row contains [height, weight] for an individual
np_person_info = np.column_stack((np_height_m, np_weight_lbs))

# Print the 2D array
print(f"\nPerson Info (Height in meters, Weight in lbs):")
print(np_person_info)

# Define a function named 'calculate_bmi' to calculate BMI from the 2D array
def calculate_bmi(person_info):
  # Extract height (column 0) and weight in lbs (column 1) from the 2D array
  heights = person_info[:, 0]
  weights_lbs = person_info[:, 1]

  # Convert weight from pounds to kg (1 lb = 0.453592 kg)
  weights_kg = weights_lbs / 2.2

  # Calculate BMI using the formula: BMI = weight (kg) / (height (m) ** 2)
  bmi_array = weights_kg / (heights ** 2)

  return bmi_array

# Call the function 'calculate_bmi' to calculate BMI for each individual from the 2D array 'np_person_info'
bmi_array = calculate_bmi(np_person_info)

# Print the BMI values for each individual
print(f"\nBMI values:")
for i, bmi in enumerate(bmi_array):
  print(f"Individual {i+1}: {bmi:.2f}")

Please enter weight values in kg separated by spaces ' ': 67 89 99 77

Weight in kg: [67. 89. 99. 77.]
Weight in lbs: [147.4 195.8 217.8 169.4]

Mean weight: 182.60 lbs
Median weight: 182.60 lbs

Please enter height values in meters separated by spaces ' ': 1.6 1.9 2.0 1.8

Person Info (Height in meters, Weight in lbs):
[[  1.6 147.4]
 [  1.9 195.8]
 [  2.  217.8]
 [  1.8 169.4]]

BMI values:
Individual 1: 26.17
Individual 2: 24.65
Individual 3: 24.75
Individual 4: 23.77


### Task 5: Filter Individuals by BMI
* Write a NumPy program to append *bmi_array* to *np_person_info*
* Filter individuals from the resulting array who have a BMI greater than 25.
* Print the filtered results.

In [ ]:
# Import NumPy library into script and gives it an alias 'np'
import numpy as np

# Initialize an empty list to store weight values
weight_kg = []

# Loop until the user provides valid input
while True:
  # Get user input as a string
  user_input = input("Please enter weight values in kg separated by spaces ' ': ")
  # Split the input into parts
  parts = user_input.split()

  # Check if at least one weight value was entered
  if len(parts) == 0:
    print("Error: Please enter at least one weight value.")
    continue

  # Try to convert all inputs to floats
  try:
    weight_kg = list(map(float, parts))

    # Check if any weight value is negative
    if any(weight < 0 for weight in weight_kg):
      print("Error: Weight values cannot be negative.")
      continue

    # Exit the loop if all conversions are successful
    break
  except ValueError:
    # Print error message if any input is not a valid number
    print("Error: All inputs must be valid numbers.")

# Convert the input list to a numpy array
np_weight_kg = np.array(weight_kg)

# Convert weight from kg to pounds (1 kg = 2.2 lbs)
np_weight_lbs = np_weight_kg * 2.2

# Print the results in kg
print(f"\nWeight in kg: {np_weight_kg}")

# Print the results in pounds
print(f"Weight in lbs: {np_weight_lbs}")

# Calculate the mean of the weights in pounds
mean_weight_lbs = np.mean(np_weight_lbs)

# Calculate the median of the weights in pounds
median_weight_lbs = np.median(np_weight_lbs)

# Print the mean weight in pounds
print(f"\nMean weight: {mean_weight_lbs:.2f} lbs")

# Print the median weight in pounds
print(f"Median weight: {median_weight_lbs:.2f} lbs")

# Initialize an empty list to store height values
height_m = []

# Loop until the user provides valid input for heights
while True:
  # Get user input as a string
  user_input = input("\nPlease enter height values in meters separated by spaces ' ': ")
  # Split the input into parts
  parts = user_input.split()

  # Check if the number of heights matches the number of weights
  if len(parts) != len(weight_kg):
    print(f"Error: Please enter exactly {len(weight_kg)} height value(s) to match the number of weights.")
    continue

  # Try to convert all inputs to floats
  try:
    height_m = list(map(float, parts))

    # Check if any height value is negative or zero
    if any(height <= 0 for height in height_m):
      print("Error: Height values must be positive.")
      continue

    # Exit the loop if all conversions are successful
    break
  except ValueError:
    # Print error message if any input is not a valid number
    print("Error: All inputs must be valid numbers.")

# Convert the height list to a numpy array
np_height_m = np.array(height_m)

# Combine height and weight arrays to create a 2D array
# Each row contains [height, weight] for an individual
np_person_info = np.column_stack((np_height_m, np_weight_lbs))

# Print the 2D array
print(f"\nPerson Info (Height in meters, Weight in lbs):")
print(np_person_info)

# Define a function named 'calculate_bmi' to calculate BMI from the 2D array
def calculate_bmi(person_info):
  # Extract height (column 0) and weight in lbs (column 1) from the 2D array
  heights = person_info[:, 0]
  weights_lbs = person_info[:, 1]

  # Convert weight from pounds to kg (1 lb = 0.453592 kg)
  weights_kg = weights_lbs / 2.2

  # Calculate BMI using the formula: BMI = weight (kg) / (height (m) ** 2)
  bmi_array = weights_kg / (heights ** 2)

  return bmi_array

# Call the function 'calculate_bmi' to calculate BMI for each individual from the 2D array 'np_person_info'
bmi_array = calculate_bmi(np_person_info)

# Print the BMI values for each individual
print(f"\nBMI values:")
for i, bmi in enumerate(bmi_array):
  print(f"Individual {i+1}: {bmi:.2f}")

# Reshape bmi_array to a column vector for appending
bmi_column = bmi_array.reshape(-1, 1)

# Append bmi_array as a new column to np_person_info
# Each row now contains [height, weight, bmi]
np_person_info = np.column_stack((np_person_info, bmi_column))

# Print the updated 2D array with BMI included
print(f"\nUpdated Person Info (Height in meters, Weight in lbs, BMI):")
print(np_person_info)

# Filter individuals with BMI greater than 25
# Create a boolean mask where BMI (column 2) is greater than 25
filtered_person_info = np_person_info[np_person_info[:, 2] > 25]

# Print the filtered results
print(f"\nIndividuals with BMI > 25 (Height in meters, Weight in lbs, BMI):")
if len(filtered_person_info) > 0:
  print(filtered_person_info)
else:
  print("No individuals have BMI greater than 25.")

Please enter weight values in kg separated by spaces ' ': 67 89 99 77

Weight in kg: [67. 89. 99. 77.]
Weight in lbs: [147.4 195.8 217.8 169.4]

Mean weight: 182.60 lbs
Median weight: 182.60 lbs

Please enter height values in meters separated by spaces ' ': 1.6 1.8 2.0 1.7

Person Info (Height in meters, Weight in lbs):
[[  1.6 147.4]
 [  1.8 195.8]
 [  2.  217.8]
 [  1.7 169.4]]

BMI values:
Individual 1: 26.17
Individual 2: 27.47
Individual 3: 24.75
Individual 4: 26.64

Updated Person Info (Height in meters, Weight in lbs, BMI):
[[  1.6        147.4         26.171875  ]
 [  1.8        195.8         27.4691358 ]
 [  2.         217.8         24.75      ]
 [  1.7        169.4         26.64359862]]

Individuals with BMI > 25 (Height in meters, Weight in lbs, BMI):
[[  1.6        147.4         26.171875  ]
 [  1.8        195.8         27.4691358 ]
 [  1.7        169.4         26.64359862]]


### Final
**updated code for readability, updated output for readability, updated filtered results to identify individual**

In [ ]:
# Import NumPy library into script and gives it an alias 'np'
import numpy as np

# Define a function named 'calculate_bmi' to calculate BMI from the 2D array
def calculate_bmi(person_info):
  """
  Calculate BMI for individuals given their height and weight.

  Parameters:
    person_info: 2D array where each row contains [ID, height in meters, weight in lbs]

  Returns:
    bmi_array: Array of BMI values for each individual
  """
  # Extract height (column 1) and weight in lbs (column 2) from the 2D array
  heights = person_info[:, 1]
  weights_lbs = person_info[:, 2]

  # Convert weight from pounds to kg (1 lb = 0.453592 kg)
  weights_kg = weights_lbs / 2.2

  # Calculate BMI using the formula: BMI = weight (kg) / (height (m) ** 2)
  bmi_array = weights_kg / (heights ** 2)

  # Return the calculated BMI array
  return bmi_array


# ===== Input: Weight Values =====
# Initialize an empty list to store weight values
weight_kg = []

# Loop until the user provides valid input
while True:
  # Get user input as a string
  user_input = input("Please enter weight values in kg separated by spaces ' ': ")

  # Split the input into parts
  parts = user_input.split()

  # Check if at least one weight value was entered
  if len(parts) == 0:
    # Print error message if no input was provided
    print("Error: Please enter at least one weight value.")
    # Continue to the next iteration of the loop
    continue

  # Try to convert all inputs to floats
  try:
    # Convert each part to float and store in weight_kg list
    weight_kg = list(map(float, parts))

    # Check if any weight value is negative
    if any(weight < 0 for weight in weight_kg):
      # Print error message if negative values are found
      print("Error: Weight values cannot be negative.")
      # Continue to the next iteration of the loop
      continue

    # Exit the loop if all conversions are successful
    break
  # Catch ValueError if conversion to float fails
  except ValueError:
    # Print error message if any input is not a valid number
    print("Error: All inputs must be valid numbers.")


# ===== Input: Height Values =====
# Initialize an empty list to store height values
height_m = []

# Loop until the user provides valid input for heights
while True:
  # Get user input as a string
  user_input = input("\nPlease enter height values in meters separated by spaces ' ': ")

  # Split the input into parts
  parts = user_input.split()

  # Check if the number of heights matches the number of weights
  if len(parts) != len(weight_kg):
    # Print error message showing exact number of height values needed
    print(f"Error: Please enter exactly {len(weight_kg)} height value(s) to match the number of weights.")
    # Continue to the next iteration of the loop
    continue

  # Try to convert all inputs to floats
  try:
    # Convert each part to float and store in height_m list
    height_m = list(map(float, parts))

    # Check if any height value is negative or zero
    if any(height <= 0 for height in height_m):
      # Print error message if non-positive values are found
      print("Error: Height values must be positive.")
      # Continue to the next iteration of the loop
      continue

    # Exit the loop if all conversions are successful
    break
  # Catch ValueError if conversion to float fails
  except ValueError:
    # Print error message if any input is not a valid number
    print("Error: All inputs must be valid numbers.")


# ===== Processing: Convert and Calculate =====
# Convert the input list to a numpy array
np_weight_kg = np.array(weight_kg)

# Convert weight from kg to pounds (1 kg = 2.2 lbs)
np_weight_lbs = np_weight_kg * 2.2

# Convert the height list to a numpy array
np_height_m = np.array(height_m)

# Create an array of individual IDs starting from 1
individual_ids = np.arange(1, len(weight_kg) + 1)

# Combine ID, height and weight arrays to create a 2D array
# Each row contains [ID, height, weight] for an individual
np_person_info = np.column_stack((individual_ids, np_height_m, np_weight_lbs))

# Calculate statistics for weights in pounds
mean_weight_lbs = np.mean(np_weight_lbs)
median_weight_lbs = np.median(np_weight_lbs)


# ===== Output: Display Results =====
# Print a newline followed by a separator line
print("\n" + "="*60)
# Print section header for weight analysis
print("WEIGHT ANALYSIS")
# Print separator line
print("="*60)
# Display weight values in kilograms
print(f"Weight in kg: {np_weight_kg}")
# Display weight values in pounds
print(f"Weight in lbs: {np_weight_lbs}")
# Display mean weight rounded to 2 decimal places
print(f"\nMean weight: {mean_weight_lbs:.2f} lbs")
# Display median weight rounded to 2 decimal places
print(f"Median weight: {median_weight_lbs:.2f} lbs")

# Print a newline followed by a separator line
print("\n" + "="*60)
# Print section header for person information without BMI
print("PERSON INFORMATION")
# Print separator line
print("="*60)
# Display format explanation for the 2D array without BMI
print("[ID, Height (m), Weight (lbs)]")
# Display the 2D array with ID, height and weight only
print(np_person_info)

# Call the function 'calculate_bmi' to calculate BMI for each individual
bmi_array = calculate_bmi(np_person_info)

# Reshape bmi_array to a column vector for appending
bmi_column = bmi_array.reshape(-1, 1)

# Append bmi_array as a new column to np_person_info
# Each row now contains [ID, height, weight, bmi]
np_person_info = np.column_stack((np_person_info, bmi_column))

# Print a newline followed by a separator line
print("\n" + "="*60)
# Print section header for BMI values
print("BMI VALUES")
# Print separator line
print("="*60)
# Loop through each BMI value with its index
for i, bmi in enumerate(bmi_array):
  # Display BMI for each individual numbered starting from 1
  print(f"Individual {i+1}: {bmi:.2f}")

# Print a newline followed by a separator line
print("\n" + "="*60)
# Print section header for person information with BMI
print("UPDATED PERSON INFORMATION WITH BMI")
# Print separator line
print("="*60)
# Display format explanation for the 2D array with BMI
print("[ID, Height (m), Weight (lbs), BMI]")
# Display the complete 2D array with ID, height, weight, and BMI
print(np_person_info)

# Print a newline followed by a separator line
print("\n" + "="*60)
# Print section header for filtered results
print("FILTERED RESULTS BMI > 25")
# Print separator line
print("="*60)
# Filter individuals with BMI greater than 25
# Create a boolean mask where BMI (column 3) is greater than 25
filtered_person_info = np_person_info[np_person_info[:, 3] > 25]

# Check if any individuals have BMI greater than 25
if len(filtered_person_info) > 0:
  # Display format explanation for filtered results
  print("[ID, Height (m), Weight (lbs), BMI]")
  # Display the filtered 2D array
  print(filtered_person_info)
# If no individuals meet the criteria
else:
  # Display message indicating no matches found
  print("No individuals have BMI greater than 25.")
# Print final separator line
print("="*60)

Please enter weight values in kg separated by spaces ' ': 55 66 77 88 99

Please enter height values in meters separated by spaces ' ': 1.5 1.7 1.7 1.9 1.8

WEIGHT ANALYSIS
Weight in kg: [55. 66. 77. 88. 99.]
Weight in lbs: [121.  145.2 169.4 193.6 217.8]

Mean weight: 169.40 lbs
Median weight: 169.40 lbs

PERSON INFORMATION
[ID, Height (m), Weight (lbs)]
[[  1.    1.5 121. ]
 [  2.    1.7 145.2]
 [  3.    1.7 169.4]
 [  4.    1.9 193.6]
 [  5.    1.8 217.8]]

BMI VALUES
Individual 1: 24.44
Individual 2: 22.84
Individual 3: 26.64
Individual 4: 24.38
Individual 5: 30.56

UPDATED PERSON INFORMATION WITH BMI
[ID, Height (m), Weight (lbs), BMI]
[[  1.           1.5        121.          24.44444444]
 [  2.           1.7        145.2         22.83737024]
 [  3.           1.7        169.4         26.64359862]
 [  4.           1.9        193.6         24.3767313 ]
 [  5.           1.8        217.8         30.55555556]]

FILTERED RESULTS BMI > 25
[ID, Height (m), Weight (lbs), BMI]
[[  3.      